"""x1

Revision ID: 4b8a43d2325a
Revises: bca042e3b943
Create Date: 2017-02-27 21:40:12.625265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8a43d2325a'
down_revision = 'bca042e3b943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'description')
    # ### end Alembic commands ###
