"""z

Revision ID: 96f1b9ecb5d7
Revises: 4b8a43d2325a
Create Date: 2017-02-27 22:38:15.206174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f1b9ecb5d7'
down_revision = '4b8a43d2325a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'context')
    # ### end Alembic commands ###
