"""permission

Revision ID: 997bcf8e7885
Revises: 666a09f141f0
Create Date: 2017-02-26 12:31:20.835958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997bcf8e7885'
down_revision = '666a09f141f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
